// Code generated by mockery v1.0.0
package mocks

import context "context"

import mock "github.com/stretchr/testify/mock"
import models "github.com/psimoesSsimoes/go-task-fanout/models"

// TaskDispatcherRepository is an autogenerated mock type for the TaskDispatcherRepository type
type TaskDispatcherRepository struct {
	mock.Mock
}

// CreateTask provides a mock function with given fields: ctx, task
func (_m *TaskDispatcherRepository) CreateTask(ctx context.Context, task models.Task) error {
	ret := _m.Called(ctx, task)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, models.Task) error); ok {
		r0 = rf(ctx, task)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
